Rename CLIENT_SETTING to JACK_CLIENT_SETTING
Test: m setup-jack-server
Change-Id: I4422776843740a5ed5d570763a903de8da2bceeb

diff --git a/server/jack-server/etc/jack b/server/jack-server/etc/jack
--- a/server/jack-server/etc/jack
+++ b/server/jack-server/etc/jack
@@ -24,7 +24,7 @@ umask 077
 #
 JACK_VERSION=${JACK_VERSION:=4.0.ENGINEERING}
 JACK_HOME="${JACK_HOME:=$HOME/.jack-server}"
-CLIENT_SETTING="${CLIENT_SETTING:=$HOME/.jack-settings}"
+JACK_CLIENT_SETTING="${JACK_CLIENT_SETTING:=$HOME/.jack-settings}"
 TMPDIR=${TMPDIR:=/tmp}
 CLIENT_TMP_DIR=$TMPDIR/jack-$USER
 JACK_CONNECTION_TIMEOUT=300
@@ -38,10 +38,10 @@ abort () { exit 255; }
 #
 # Load client settings
 #
-if [ -f "$CLIENT_SETTING" ]; then
-  source "$CLIENT_SETTING"
+if [ -f "$JACK_CLIENT_SETTING" ]; then
+  source "$JACK_CLIENT_SETTING"
 else
-  echo "Cannot find settings at '$CLIENT_SETTING'" >&2
+  echo "Cannot find settings at '$JACK_CLIENT_SETTING'" >&2
   abort
 fi
 
