Make start-server check installation
If installation dir is missing just exit immediately.

Bug: 26259965

Change-Id: Ie278e0f33cd9765a977c9653cb69f97ea8ab4add

diff --git a/server/jack-server/etc/jack-admin b/server/jack-server/etc/jack-admin
--- a/server/jack-server/etc/jack-admin
+++ b/server/jack-server/etc/jack-admin
@@ -441,6 +441,11 @@ case $COMMAND in
 
 
   start-server)
+    if [ ! -d "$JACK_HOME" ]; then
+      echo "Jack server installation not found" >&2
+      abort
+    fi
+
     isServerRunning
     RUNNING=$?
     if [ "$RUNNING" = 0 ]; then
