Introduce jack-admin dump-report
Report is a zip and is dumped in current directory.

Bug: 26176046

Change-Id: I7857d1c6ed7a7b7347c3925f2b04e4976de94377

diff --git a/server/jack-server/etc/jack-admin b/server/jack-server/etc/jack-admin
--- a/server/jack-server/etc/jack-admin
+++ b/server/jack-server/etc/jack-admin
@@ -69,7 +69,7 @@ EOT
 fi
 
 usage () {
-  echo "Usage : $0 [ install-server <launcher.jar> <server.jar> | uninstall-server | list <program> | update <program> <program.jar> | start-server | stop-server | kill-server | list-server | server-stat | server-log | server-gc | cleanup-server]"
+  echo "Usage : $0 [ install-server <launcher.jar> <server.jar> | uninstall-server | list <program> | update <program> <program.jar> | start-server | stop-server | kill-server | list-server | server-stat | server-log | server-gc | cleanup-server | dump-report]"
 }
 
 abort () { exit 255; }
@@ -525,6 +525,73 @@ case $COMMAND in
       rm "${file%.deleted}"
       rm "$file"
     done
+    exit 0 ;;
+
+
+  dump-report)
+    if [ ! -d "$JACK_HOME" ]; then
+      echo "Failed to locate Jack server installation" >&2
+      abort
+    fi
+
+    echo "Creating report"
+    REPORT="jack-report.$$.zip"
+    REPORT_PATH="$(pwd)/$REPORT"
+    REPORT_INFO="$JACK_HOME/report.$$.txt"
+
+    if [ -e "$REPORT" ]; then
+      echo "Failed to create Jack server report '$REPORT', file already exists" >&2
+      abort
+    fi
+
+    trap 'rm -f "$REPORT_INFO" 2>/dev/null;' EXIT
+
+    echo "Dumping Jack server stacks"
+    echo >>"$REPORT_INFO"
+    echo "\$ ps -A -o \"pid args\" | grep $LAUNCHER_NAME | grep -v grep | awk '{print $1}' |  xargs kill -3" >>"$REPORT_INFO"
+            (ps -A -o  "pid args"  | grep $LAUNCHER_NAME | grep -v grep | awk '{print $1}' |  xargs kill -3) >>"$REPORT_INFO" 2>&1
+
+    echo "Collecting info to '$REPORT_INFO'"
+    date >>"$REPORT_INFO" 2>&1
+
+    echo "Getting current user id"
+    echo >>"$REPORT_INFO"
+    echo "\$ id -u" >>"$REPORT_INFO"
+             id -u  >>"$REPORT_INFO"
+
+    echo "Listing Jack server process"
+    echo >>"$REPORT_INFO"
+    echo "\$ ps -A -o \"uid pid args\" | grep $LAUNCHER_NAME | grep -v grep" >>"$REPORT_INFO"
+            (ps -A -o  "uid pid args"  | grep $LAUNCHER_NAME | grep -v grep) >>"$REPORT_INFO" 2>&1
+
+    echo "Listing process using Jack server service port $SERVER_PORT_SERVICE"
+    echo >>"$REPORT_INFO"
+    echo "\$ lsof -i TCP:$SERVER_PORT_SERVICE -l" >>"$REPORT_INFO"
+             lsof -i TCP:$SERVER_PORT_SERVICE -l  >>"$REPORT_INFO" 2>&1
+
+    echo "Listing process using Jack server admin port $SERVER_PORT_ADMIN"
+    echo >>"$REPORT_INFO"
+    echo "\$ lsof -i TCP:$SERVER_PORT_ADMIN -l" >>"$REPORT_INFO"
+             lsof -i TCP:$SERVER_PORT_ADMIN -l  >>"$REPORT_INFO" 2>&1
+
+    echo "Collecting Jack client configuration '$CLIENT_SETTING'"
+    echo >>"$REPORT_INFO"
+    echo "\$ cat \"\$CLIENT_SETTING\"" >>"$REPORT_INFO"
+             cat   "$CLIENT_SETTING"   >>"$REPORT_INFO" 2>&1
+
+    echo "Listing Jack server installation dir '$JACK_HOME'"
+    echo >>"$REPORT_INFO"
+    echo "\$ cd \"\$JACK_HOME\"; ls -l -R -n ." >>"$REPORT_INFO"
+            (cd   "$JACK_HOME" ; ls -l -R -n .  >>"$REPORT_INFO" 2>&1)
+
+    echo "Collecting Jack server stats"
+    echo >>"$REPORT_INFO"
+    echo "\$ jack-admin server-stat" >>"$REPORT_INFO"
+             "$0"       server-stat  >>"$REPORT_INFO" 2>&1
+
+    echo "Zipping Jack server installation dir '$JACK_HOME' except keys and certificates"
+    (cd "$JACK_HOME"; zip --exclude \*.pem \*.jks --recurse-paths "$REPORT_PATH" .) >/dev/null
+    echo "Jack server report saved in '$REPORT'. Consider reviewing content before publication"
     exit 0 ;;
 
 
