Rework Jack server
Removes usage of fifo.
Allows support of multiple Jack versions in the same server.
Prepare support for Jill.

Server must now be installed in home directory.

Bug: 21491926

Change-Id: I1c3a34ddaa58cb3e4f92d86691e444d4753c77ed

diff --git a/jack/etc/jack b/jack/etc/jack
--- a/jack/etc/jack
+++ b/jack/etc/jack
@@ -22,99 +22,53 @@ umask 077
 #
 # Settings
 #
-LOCAL_SETTING="$HOME/.jack"
+JACK_VERSION=${JACK_VERSION:=3.1.ENGINEERING}
+JACK_HOME="${JACK_HOME:=$HOME/.jack-home}"
+CLIENT_SETTING="${CLIENT_SETTING:=$HOME/.jack-client}"
 TMPDIR=${TMPDIR:=/tmp}
-SERVER_DIR=$TMPDIR/jack-$USER
+CLIENT_TMP_DIR=$TMPDIR/jack-$USER
 
 #
-# Load local settings
+# Load client settings
 #
-if [[ -f "$LOCAL_SETTING" ]]; then
-  source "$LOCAL_SETTING"
+if [ -f "$CLIENT_SETTING" ]; then
+  source "$CLIENT_SETTING"
 fi
 
 #
-# Create or update local settings if needed
+# Create or update client settings if needed
 #
-if [[ ! -f "$LOCAL_SETTING" || $SETTING_VERSION -lt 3 ]]; then
-  echo "Writing local settings in" $LOCAL_SETTING
-  cat >"$LOCAL_SETTING.$$" <<-EOT
+if [[ ! -f "$CLIENT_SETTING" || $SETTING_VERSION -lt 4 ]]; then
+  echo "Writing client settings in" $CLIENT_SETTING
+  cat >"$CLIENT_SETTING.$$" <<-EOT
 	# Server settings
-	SERVER=${SERVER:=true}
-	SERVER_PORT_SERVICE=${SERVER_PORT_SERVICE:=8072}
-	SERVER_PORT_ADMIN=${SERVER_PORT_ADMIN:=8073}
-	SERVER_COUNT=${SERVER_COUNT:=1}
-	SERVER_NB_COMPILE=${SERVER_NB_COMPILE:=4}
-	SERVER_TIMEOUT=${SERVER_TIMEOUT:=60}
-	JACK_MAIN_COMMAND=\${JACK_MAIN_COMMAND:=""}
-	JACK_SERVER_COMMAND=\${JACK_SERVER_COMMAND:=""}
-	SERVER_LOG=\${SERVER_LOG:=\$SERVER_DIR/jack-\$SERVER_PORT_SERVICE.log}
-	JACK_VM_COMMAND=\${JACK_VM_COMMAND:=java}
-	# Internal, do not touch
-	SETTING_VERSION=3
-EOT
-  ln -f "$LOCAL_SETTING.$$" "$LOCAL_SETTING"
-  rm "$LOCAL_SETTING.$$"
-  source "$LOCAL_SETTING"
-fi
+	SERVER_HOST=${SERVER_HOST:=127.0.0.1}
+	SERVER_PORT_SERVICE=${SERVER_PORT_SERVICE:=8074}
+	SERVER_PORT_ADMIN=${SERVER_PORT_ADMIN:=8075}
 
-#
-# If not in server mode, exec jack
-#
-if [ "$SERVER" != "true" ]; then
-  if [ -z "$JACK_MAIN_COMMAND" ]; then
-    JACK_MAIN_COMMAND=java -Djava.io.tmpdir=$TMPDIR -jar $JACK_JAR
-  fi
-  exec $JACK_MAIN_COMMAND "$@"
-  echo "ERROR: Cannot succeed to launch Jack without Jack server" >&2
-  exit 255
+	# Internal, do not touch
+	SETTING_VERSION=4
+EOT
+  ln -f "$CLIENT_SETTING.$$" "$CLIENT_SETTING"
+  rm "$CLIENT_SETTING.$$"
+  source "$CLIENT_SETTING"
 fi
 
 #
 # Prepare compilation
 #
-JACK_DIR="$SERVER_DIR/jack-task-$$/"
-JACK_OUT="$JACK_DIR/out"
-JACK_ERR="$JACK_DIR/err"
-JACK_CLI="$JACK_DIR/cli"
-JACK_EXIT="$JACK_DIR/exit"
 JACK_PWD="$PWD"
-JACK_CLIENT_LOG=${JACK_CLIENT_LOG:="$SERVER_DIR/client.log"}
-
-if [ -z "$JACK_SERVER_COMMAND" ]; then
-  JACK_SERVER_COMMAND="java -Djava.io.tmpdir=$TMPDIR -cp $JACK_JAR com.android.jack.server.JackSimpleServer"
-fi
-
-
-mkdir "$SERVER_DIR" 2>/dev/null
+JACK_DIR="$CLIENT_TMP_DIR/jack-task-$$/"
+JACK_EXIT="$JACK_DIR/exit"
 
 # Cleanup
-trap 'rm -f "$JACK_OUT" "$JACK_ERR" "$JACK_CLI" "$JACK_EXIT" 2>>$JACK_CLIENT_LOG; rmdir "$JACK_DIR" 2>>$JACK_CLIENT_LOG;' EXIT
+trap 'rm -f "$JACK_EXIT" 2>/dev/null; rmdir "$JACK_DIR";' EXIT
 
+mkdir "$CLIENT_TMP_DIR" 2>/dev/null || (exit 0)
 set -o errexit
+mkdir "$JACK_DIR"
 
-# Create fifos and files for a task
-mkdir  "$JACK_DIR"
-mkfifo "$JACK_OUT"
-mkfifo "$JACK_ERR"
-touch  "$JACK_CLI" "$JACK_EXIT"
-
-# Try to cleanup if interrupted
-abort () { echo $(uptime) >>$JACK_CLIENT_LOG; kill -9 $PID_OUT $PID_ERR 2>>$JACK_CLIENT_LOG; wait $PID_OUT $PID_ERR 2>>$JACK_CLIENT_LOG; exit 255; }
-trap 'abort' SIGHUP SIGINT SIGQUIT SIGTERM ERR
-
-# Redirect output and error
-cat <"$JACK_OUT" >&1 &
-PID_OUT=$!
-cat <"$JACK_ERR" >&2 &
-PID_ERR=$!
-
-# Prepare the working directory and command line
-echo -n \"$PWD\" "" >"$JACK_CLI"
-for i in "$@"; do
-  echo -n \"$i\" "" >>"$JACK_CLI"
-done
-echo >>"$JACK_CLI"
+abort () { exit 255; }
 
 #
 # Launch the compilation
@@ -123,40 +77,41 @@ echo >>"$JACK_CLI"
 set +o errexit
 trap ERR
 
+# put arguments in a non array variable
+ARGS=""
+for i in "$@"; do
+  ARGS="$ARGS $i"
+done
+
+exec 3>&1
+exec 4>&2
+
 RETRY_LAUNCH=1
 RETRY_SESSION=3
-DELAY_CONNECT=30
-
-
 # Launch compilation
-DATE_CONNECT=$(date +%s)
 while true; do
-  CURL_TIME=$(date +%H:%M:%S)
-  HTTP_CODE=$(curl --fail --silent --data @- --output "$JACK_EXIT" --write-out %{http_code} --connect-timeout 10 --no-proxy 127.0.0.1:$SERVER_PORT_SERVICE http://127.0.0.1:$SERVER_PORT_SERVICE/jack <<< "+ $JACK_OUT $JACK_ERR $JACK_CLI")
+
+  HTTP_CODE=$(curl -f \
+       --output >(tee >(sed -n -e 's/^E|\(.*\)$/\1/p' >&4 ) | tee >(sed -n -e 's/^X|\(.*\)$/\1/p' >$JACK_EXIT) | sed -n -e 's/^O|\(.*\)$/\1/p' >&3) \
+       --no-buffer --write-out '%{http_code}\n' --silent --connect-timeout 10 \
+       -X POST \
+       -H "Accept: application/vnd.jack.command-out;version=1" \
+       -F "cli=$ARGS;type=plain/text" \
+       -F "version=$JACK_VERSION;type=application/vnd.jack.select-exact;version=1" \
+       -F "pwd=$JACK_PWD;type=plain/text" \
+       --no-proxy ${SERVER_HOST}:$SERVER_PORT_SERVICE \
+       http://${SERVER_HOST}:$SERVER_PORT_SERVICE/jack \
+       )
+
   CURL_CODE=$?
   JACK_CODE=$(cat "$JACK_EXIT")
-  echo "CURL: $$ - $CURL_TIME - $CURL_CODE - $HTTP_CODE - $JACK_CODE" >>$JACK_CLIENT_LOG
   if [ $CURL_CODE -eq 0 ]; then
     # No problem, let's go
     break;
   elif [ $CURL_CODE -eq 7 ]; then
     # Failed to connect
-    if [ $(date +%s) -ge $DATE_CONNECT ]; then
-      if [ $RETRY_LAUNCH -eq 0 ]; then
-        echo "ERROR: Cannot launch Jack server" >&2
-        abort
-      else
-        let RETRY_LAUNCH=RETRY_LAUNCH-1
-        echo "Launching background server" $JACK_SERVER_COMMAND
-        $JACK_SERVER_COMMAND $SERVER_PORT_SERVICE $SERVER_PORT_ADMIN $SERVER_COUNT $SERVER_NB_COMPILE $SERVER_TIMEOUT &
-        # New server, let's try a bit to connect
-        let DATE_CONNECT=$(date +%s)+$DELAY_CONNECT;
-      fi
-    else
-      sleep 0.2 2>/dev/null
-    fi
-    # Trying with a new connection, let's retry session 3 times max
-    RETRY_SESSION=3
+    echo "ERROR: Cannot connect to Jack server" >&2
+    abort
   elif  [ $CURL_CODE -eq 22 ]; then
     # Http code not OK, let's decode and abort
     if [ $HTTP_CODE -eq 401 ]; then
@@ -169,7 +124,7 @@ while true; do
       abort
     else
       # Other
-      echo "ERROR: Internal unknown error ($HTTP_CODE), try other ports in ~/.jack, or see Jack server log" >&2
+      echo "ERROR: Internal unknown error ($HTTP_CODE), try other ports in $CLIENT_SETTING, or see Jack server log" >&2
       abort
     fi
   else
@@ -182,10 +137,6 @@ while true; do
     fi
   fi
 done
-
-# Wait for termination
-wait $PID_OUT
-wait $PID_ERR
 
 # Exit
 exit $JACK_CODE
diff --git a/jack/etc/jack-admin b/jack/etc/jack-admin
--- a/jack/etc/jack-admin
+++ b/jack/etc/jack-admin
@@ -22,150 +22,395 @@ umask 077
 #
 # Settings
 #
-LOCAL_SETTING="$HOME/.jack"
+JACK_HOME="${JACK_HOME:=$HOME/.jack-home}"
+CLIENT_SETTING="${CLIENT_SETTING:=$HOME/.jack-client}"
 TMPDIR=${TMPDIR:=/tmp}
-SERVER_DIR=$TMPDIR/jack-$USER
+JACK_SERVER_VM_ARGUMENTS="${JACK_SERVER_VM_ARGUMENTS:=-Dfile.encoding=UTF-8 -XX:+TieredCompilation}"
+
+LAUNCHER_JAR="$JACK_HOME/launcher.jar"
+LAUNCHER_NAME=com.android.jack.launcher.ServerLauncher
+
 
 #
-# Load local settings
+# Load client settings
 #
-if [[ -f "$LOCAL_SETTING" ]]; then
-  source "$LOCAL_SETTING"
+if [ -f "$CLIENT_SETTING" ]; then
+  source "$CLIENT_SETTING"
 fi
 
 #
-# Create or update local settings if needed
+# Create or update client settings if needed
 #
-if [[ ! -f "$LOCAL_SETTING" || $SETTING_VERSION -lt 3 ]]; then
-  echo "Writing local settings in" $LOCAL_SETTING
-  cat >"$LOCAL_SETTING.$$" <<-EOT
+if [[ ! -f "$CLIENT_SETTING" || $SETTING_VERSION -lt 4 ]]; then
+  echo "Writing client settings in" $CLIENT_SETTING
+  cat >"$CLIENT_SETTING.$$" <<-EOT
 	# Server settings
-	SERVER=${SERVER:=true}
-	SERVER_PORT_SERVICE=${SERVER_PORT_SERVICE:=8072}
-	SERVER_PORT_ADMIN=${SERVER_PORT_ADMIN:=8073}
-	SERVER_COUNT=${SERVER_COUNT:=1}
-	SERVER_NB_COMPILE=${SERVER_NB_COMPILE:=4}
-	SERVER_TIMEOUT=${SERVER_TIMEOUT:=60}
-	JACK_MAIN_COMMAND=\${JACK_MAIN_COMMAND:=""}
-	JACK_SERVER_COMMAND=\${JACK_SERVER_COMMAND:=""}
-	SERVER_LOG=\${SERVER_LOG:=\$SERVER_DIR/jack-\$SERVER_PORT_SERVICE.log}
-	JACK_VM_COMMAND=\${JACK_VM_COMMAND:=java}
+	SERVER_HOST=${SERVER_HOST:=127.0.0.1}
+	SERVER_PORT_SERVICE=${SERVER_PORT_SERVICE:=8074}
+	SERVER_PORT_ADMIN=${SERVER_PORT_ADMIN:=8075}
+
 	# Internal, do not touch
-	SETTING_VERSION=3
+	SETTING_VERSION=4
 EOT
-  ln -f "$LOCAL_SETTING.$$" "$LOCAL_SETTING"
-  rm "$LOCAL_SETTING.$$"
-  source "$LOCAL_SETTING"
+  ln -f "$CLIENT_SETTING.$$" "$CLIENT_SETTING"
+  rm "$CLIENT_SETTING.$$"
+  source "$CLIENT_SETTING"
 fi
 
-mkdir "$SERVER_DIR" 2>/dev/null
+usage () {
+  echo "Usage : $0 [ install-server <launcher.jar> <server.jar> | list <program> | install <program> <program.jar> | start-server | stop-server | kill-server | list-server | server-stat ]"
+}
+
+abort () { exit 255; }
+
+#
+# $1: curl command status
+# $2: HTTP status
+#
+handleHttpErrors() {
+  if [ $1 -eq 0 ]; then
+    # No problem, let's go
+    return 0;
+  elif [ $1 -eq 7 ]; then
+    echo "ERROR: No Jack server running" >&2
+    abort
+  elif  [ $1 -eq 22 ]; then
+    # Http code not OK, let's decode and abort
+    if [ $2 -eq 401 ]; then
+      # 401: Unauthorized
+      echo "ERROR: Security problem, see Jack server log" >&2
+      abort
+    elif [ $2 -eq 400 ]; then
+      # 400: Bad request
+      echo "ERROR: Bad request, see Jack server log" >&2
+      abort
+    else
+      # Other
+      echo "ERROR: Internal unknown error $HTTP_CODE, try other ports in ~/.jack, or see Jack server log" >&2
+      abort
+    fi
+  else
+    # In case of partial, timeout, empty respond, network error, let's retry
+    if [ $RETRY_SESSION -eq 0 ]; then
+      echo "ERROR: Communication error with Jack server $CURL_CODE" >&2
+      abort
+    else
+      let RETRY_SESSION=RETRY_SESSION-1
+      return 1;
+    fi
+  fi
+}
+
+#
+# $1: program name
+# $2: jar of the program
+#
+installProgram () {
+  RETRY_SESSION=3
+  DONE=1
+  while [ "$DONE" -ne 0 ]; do
+    HTTP_CODE=$(curl -f \
+         --output >(cat >&3) \
+         --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
+         -X PUT \
+         -F "jar=@$2;type=application/octet-stream" \
+         -F "force=$FORCE_INSTALLATION;type=text/plain" \
+         --no-proxy ${SERVER_HOST}:$SERVER_PORT_ADMIN \
+         http://${SERVER_HOST}:$SERVER_PORT_ADMIN/$1 \
+         )
+    handleHttpErrors $? $HTTP_CODE
+    DONE=$?
+  done
+
+  if [ "$1" == server ]; then
+    waitServerStarted
+  fi
+}
+
+isServerRunning () {
+  RETRY_SESSION=3
+  DONE=1
+  while [ "$DONE" -ne 0 ]; do
+    HTTP_CODE=$(curl -f \
+         --output >(cat >/dev/null) \
+         --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
+         -X GET \
+         -H "Accept: text/plain" \
+         --no-proxy ${SERVER_HOST}:$SERVER_PORT_ADMIN \
+         http://${SERVER_HOST}:$SERVER_PORT_ADMIN/server \
+         )
+    CURL_CODE=$?
+    if [ $CURL_CODE -eq 0 ]; then
+      # No problem, let's go
+      return 0;
+    elif [ $CURL_CODE -eq 7 ]; then
+      return 1
+    elif  [ $CURL_CODE -eq 22 ]; then
+      # Http code not OK, let's decode and abort
+      if [ $HTTP_CODE -eq 401 ]; then
+        # 401: Unauthorized
+        echo "ERROR: Security problem, see Jack server log" >&2
+        abort
+      elif [ $HTTP_CODE -eq 400 ]; then
+        # 400: Bad request
+        echo "ERROR: Bad request, see Jack server log" >&2
+        abort
+      else
+        # Other
+        echo "ERROR: Internal unknown error $HTTP_CODE, try other ports in ~/.jack, or see Jack server log" >&2
+        abort
+      fi
+    else
+      # In case of partial, timeout, empty respond, network error, let's retry
+      if [ $RETRY_SESSION -eq 0 ]; then
+        echo "ERROR: Communication error with Jack server $CURL_CODE" >&2
+        abort
+      else
+        let RETRY_SESSION=RETRY_SESSION-1
+      fi
+    fi
+  done
+}
+
+startServer () {
+  isServerRunning
+  RUNNING=$?
+  if [ "$RUNNING" = 0 ]; then
+    echo "Server is already running"
+  else
+    JACK_SERVER_COMMAND="java -Djava.io.tmpdir=$TMPDIR $JACK_SERVER_VM_ARGUMENTS -cp $LAUNCHER_JAR $LAUNCHER_NAME"
+    echo "Launching Jack server" $JACK_SERVER_COMMAND
+    $JACK_SERVER_COMMAND &
+  fi
+}
+
+waitServerStarted () {
+  RETRY_SESSION=6
+  DONE=1
+  while [ "$DONE" -ne 0 ]; do
+    HTTP_CODE=$(curl -f \
+         --output >(cat >/dev/null) \
+         --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
+         -X GET \
+         -H "Accept: text/plain" \
+         --no-proxy ${SERVER_HOST}:$SERVER_PORT_ADMIN \
+         http://${SERVER_HOST}:$SERVER_PORT_ADMIN/server \
+         )
+    CURL_CODE=$?
+    if [ $CURL_CODE -eq 0 ]; then
+      # No problem, let's go
+      DONE=0;
+    elif [ $CURL_CODE -eq 7 ]; then
+      if [ $RETRY_SESSION -eq 0 ]; then
+        echo "ERROR: No Jack server running" &>2
+        abort
+      else
+        let RETRY_SESSION=RETRY_SESSION-1
+        sleep 1;
+      fi
+    elif  [ $CURL_CODE -eq 22 ]; then
+      # Http code not OK, let's decode and abort
+      if [ $HTTP_CODE -eq 401 ]; then
+        # 401: Unauthorized
+        echo "ERROR: Security problem, see Jack server log" >&2
+        abort
+      elif [ $HTTP_CODE -eq 400 ]; then
+        # 400: Bad request
+        echo "ERROR: Bad request, see Jack server log" >&2
+        abort
+      else
+        # Other
+        echo "ERROR: Internal unknown error $HTTP_CODE, try other ports in ~/.jack, or see Jack server log" >&2
+        abort
+      fi
+    else
+      # In case of partial, timeout, empty respond, network error, let's retry
+      if [ $RETRY_SESSION -eq 0 ]; then
+        echo "ERROR: Communication error with Jack server $CURL_CODE" >&2
+        abort
+      else
+        let RETRY_SESSION=RETRY_SESSION-1
+      fi
+    fi
+  done
+}
+#
+# $1: program name
+#
+listProgramVersion () {
+  RETRY_SESSION=3
+  DONE=1
+  while [ "$DONE" -ne 0 ]; do
+    HTTP_CODE=$(curl -f \
+         --output >(cat >&3) \
+         --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
+         -X GET \
+         -H "Accept: text/plain" \
+         --no-proxy ${SERVER_HOST}:$SERVER_PORT_ADMIN \
+         http://${SERVER_HOST}:$SERVER_PORT_ADMIN/$1 \
+         )
+    handleHttpErrors $? $HTTP_CODE
+    DONE=$?
+  done
+}
 
 #
 # Decoding argument
 #
-
-if [ $# -ne 1 ]
+if [ $# -eq 0 ]
 then
-        echo "Usage : $0 [ start-server | stop-server | kill-server | list-server | server-stat ]"
-        exit 255
+  usage
+  abort
 fi
 
+set +o errexit
+
+exec 3>&1
+
+FORCE_INSTALLATION=false
 case $1 in
+  force-install-server)
+    FORCE_INSTALLATION=true
+    COMMAND=install-server;;
+  force-install)
+    FORCE_INSTALLATION=true
+    COMMAND=install;;
+  *)
+    COMMAND=$1;;
+esac
+
+case $COMMAND in
+  install-server)
+    if [ $# -lt 3 ]; then
+      usage
+      abort
+    fi
+    if [ $# -gt 4 ]; then
+      usage
+      abort
+    fi
+    if [ ! -r "$2" ]; then
+      echo "ERROR: \"$2\" is not a readable file" 1>&2
+      usage
+      abort
+    fi
+     if [ ! -r "$3" ]; then
+      echo "ERROR: \"$3\" is not a readable file" 1>&2
+      usage
+      abort
+    fi
+
+    if [ ! -d "$JACK_HOME" ]; then
+      echo Installing jack server in \"$JACK_HOME\"
+      mkdir -p "$JACK_HOME"
+      cp $2 "$LAUNCHER_JAR"
+      cp $3 "$JACK_HOME/server-1.jar"
+      mkdir "$JACK_HOME"/logs
+      startServer
+      waitServerStarted
+    else
+      echo \"$JACK_HOME\" already exists. Skipping installation of launcher
+      startServer
+      waitServerStarted
+      installProgram server $3
+    fi
+    exit 0 ;;
+
+
+  list)
+    if [ $# -ne 2 ]
+    then
+      usage
+      abort
+    fi
+
+    listProgramVersion $2 ;;
+
+
+  install)
+    if [ $# -ne 3 ]; then
+      usage
+      abort
+    fi
+
+    if [ ! -r "$3" ]; then
+      echo "ERROR: \"$3\" is not a readable file" 1>&2
+      usage
+      abort
+    fi
+    installProgram $2 $3 ;;
+
+
   stop-server)
     echo "Stopping background server"
-    CMD="stop" ;;
+
+    RETRY_SESSION=3
+    DONE=1
+    while [ "$DONE" -ne 0 ]; do
+      HTTP_CODE=$(curl -f \
+           --output >(cat >&3) \
+           --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
+           -X POST \
+           --no-proxy ${SERVER_HOST}:$SERVER_PORT_ADMIN \
+           http://${SERVER_HOST}:$SERVER_PORT_ADMIN/server/stop \
+           )
+      handleHttpErrors $? $HTTP_CODE
+      DONE=$?
+    done ;;
+
+
   server-stat)
     echo "Getting statistic from background server"
-    CMD="stat" ;;
+
+    RETRY_SESSION=3
+    DONE=1
+    while [ "$DONE" -ne 0 ]; do
+      HTTP_CODE=$(curl -f \
+           --output >(cat >&3) \
+           --no-buffer --write-out '%{http_code}' --silent --connect-timeout 10 \
+           -X GET \
+           -H "Accept: text/plain" \
+           --no-proxy ${SERVER_HOST}:$SERVER_PORT_ADMIN \
+           http://${SERVER_HOST}:$SERVER_PORT_ADMIN/stat \
+           )
+      handleHttpErrors $? $HTTP_CODE
+      DONE=$?
+    done ;;
+
+
   server-log)
     echo "Command server-log is not supported any more" 1>&2
-    exit 255 ;;
+    abort ;;
+
+
   kill-server)
     echo "Killing background server"
-    kill $(ps aux | grep JackSimpleServer | grep -v grep | awk '{print $2}') 2>/dev/null
+    kill $(ps aux | grep $LAUNCHER_NAME | grep -v grep | awk '{print $2}') 2>/dev/null
     if [ $? -ne 0 ]; then
       echo "ERROR: No Jack server to kill" >&2
       exit 2
     else
       exit 0
     fi ;;
+
+
   list-server)
-    ps aux | grep JackSimpleServer | grep -v grep
+    ps aux | grep $LAUNCHER_NAME | grep -v grep
     exit $? ;;
+
+
   start-server)
-    if [ -z "$JACK_SERVER_COMMAND" ]; then
-      JACK_SERVER_COMMAND="java -Djava.io.tmpdir=$TMPDIR -cp $JACK_JAR com.android.jack.server.JackSimpleServer"
-    fi
-    echo "Launching Jack server" $JACK_SERVER_COMMAND
-    $JACK_SERVER_COMMAND $SERVER_PORT_SERVICE $SERVER_PORT_ADMIN $SERVER_COUNT $SERVER_NB_COMPILE $SERVER_TIMEOUT &
+    startServer
+    waitServerStarted
     exit 0 ;;
+
+
   *)
-    echo "Usage : $0 [ start-server | stop-server | kill-server | list-server | server-stat ]"
-    exit 255 ;;
+    usage
+    abort ;;
 esac
 
-#
-# Send command
-#
-
-set +o errexit
-
-# Try to cleanup if interrupted
-# Cleanup
-JACK_EXIT="$SERVER_DIR/admin-$$"
-trap 'rm -f "$JACK_EXIT" 2>/dev/null;' EXIT
-
-RETRY_SESSION=3
-DELAY_CONNECT=3
-
-
-# Send command to Jack server
-DATE_CONNECT=$(date +%s)
-while true; do
-  HTTP_CODE=$(curl --fail --silent --output $JACK_EXIT --write-out %{http_code} --connect-timeout 5 --no-proxy 127.0.0.1:$SERVER_PORT_ADMIN http://127.0.0.1:$SERVER_PORT_ADMIN/$CMD)
-  CURL_CODE=$?
-  if [ $CURL_CODE -eq 0 ]; then
-    # No problem, let's go
-    break;
-  elif [ $CURL_CODE -eq 7 ]; then
-    # Failed to connect
-    if [ $(date +%s) -ge $DATE_CONNECT ]; then
-        echo "ERROR: No Jack server running"
-        exit 255
-    else
-      sleep 0.2 2>/dev/null
-    fi
-    # Trying with a new connection, let's retry session 3 times max
-    RETRY_SESSION=3
-  elif  [ $CURL_CODE -eq 22 ]; then
-    # Http code not OK, let's decode and abort
-    if [ $HTTP_CODE -eq 401 ]; then
-      # 401: Unauthorized
-      echo "ERROR: Security problem, see Jack server log" >&2
-      exit 255
-    elif [ $HTTP_CODE -eq 400 ]; then
-      # 400: Bad request
-      echo "ERROR: Bad request, see Jack server log" >&2
-      exit 255
-    else
-      # Other
-      echo "ERROR: Internal unknown error ($HTTP_CODE), try other ports in ~/.jack, or see Jack server log" >&2
-      exit 255
-    fi
-  else
-    # In case of partial, timeout, empty respond, network error, let's retry
-    if [ $RETRY_SESSION -eq 0 ]; then
-      echo "ERROR: Communication error with Jack server ($CURL_CODE)" >&2
-      exit 255
-    else
-      let RETRY_SESSION=RETRY_SESSION-1
-    fi
-  fi
-done
 
 # Exit
-if [ -r $JACK_EXIT ]; then
-  cat <$JACK_EXIT 2>/dev/null
-fi
 
 exit 0
