Fix internal error message
Change-Id: I020a0d6138120f802c2b93e1e665cb03ffc953c9

diff --git a/jack/etc/jack b/jack/etc/jack
--- a/jack/etc/jack
+++ b/jack/etc/jack
@@ -126,7 +126,7 @@ while true; do
       abort
     else
       # Other
-      echo "ERROR: Internal unknown error ($HTTP_CODE), try other ports in $CLIENT_SETTING, or see Jack server log" >&2
+      echo "ERROR: Internal unknown error ($HTTP_CODE), try other ports or see Jack server log" >&2
       abort
     fi
   else
diff --git a/jack/etc/jack-admin b/jack/etc/jack-admin
--- a/jack/etc/jack-admin
+++ b/jack/etc/jack-admin
@@ -86,7 +86,7 @@ handleHttpErrors() {
       abort
     else
       # Other
-      echo "ERROR: Internal unknown error $HTTP_CODE, try other ports in ~/.jack, or see Jack server log" >&2
+      echo "ERROR: Internal unknown error $HTTP_CODE, try other ports or see Jack server log" >&2
       abort
     fi
   else
@@ -159,7 +159,7 @@ isServerRunning () {
         abort
       else
         # Other
-        echo "ERROR: Internal unknown error $HTTP_CODE, try other ports in ~/.jack, or see Jack server log" >&2
+        echo "ERROR: Internal unknown error $HTTP_CODE, try other ports or see Jack server log" >&2
         abort
       fi
     else
@@ -229,7 +229,7 @@ waitServerStarted () {
         abort
       else
         # Other
-        echo "ERROR: Internal unknown error $HTTP_CODE, try other ports in ~/.jack, or see Jack server log" >&2
+        echo "ERROR: Internal unknown error $HTTP_CODE, try other ports or see Jack server log" >&2
         abort
       fi
     else
@@ -384,7 +384,7 @@ case $COMMAND in
               abort
             else
               # Other
-              echo "ERROR: Internal unknown error $HTTP_CODE, try other ports in ~/.jack, or see Jack server log" >&2
+              echo "ERROR: Internal unknown error $HTTP_CODE, try other ports or see Jack server log" >&2
               abort
             fi
           else
