Let Jack-admin install-server only install the file
Remove start of server
Remove update of server if an installation was already present

Change-Id: I33b8ab4caefd926c65fe9c0d101b3716d99b2901

diff --git a/jack/etc/jack-admin b/jack/etc/jack-admin
--- a/jack/etc/jack-admin
+++ b/jack/etc/jack-admin
@@ -278,9 +278,6 @@ set +o errexit
 
 FORCE_INSTALLATION=false
 case $1 in
-  force-install-server)
-    FORCE_INSTALLATION=true
-    COMMAND=install-server;;
   force-update)
     FORCE_INSTALLATION=true
     COMMAND=update;;
@@ -315,13 +312,9 @@ case $COMMAND in
       cp $2 "$LAUNCHER_JAR"
       cp $3 "$JACK_HOME/server-1.jar"
       mkdir "$JACK_HOME"/logs
-      startServer
-      waitServerStarted
     else
-      echo \"$JACK_HOME\" already exists. Skipping installation of launcher
-      startServer
-      waitServerStarted
-      updateProgram server $3
+      echo "ERROR: \"$JACK_HOME\" already exists" 1>&2
+      abort
     fi
     exit 0 ;;
 
